// The one deliberate, documented exception to engine-derivation.
//
// The engine ships `docs/oss/mruby/dragonruby-mruby-*.patch` — DIFFS against
// upstream mruby 3.0.0 (`git checkout 3.0.0` per dragonruby-mruby.readme.txt,
// then apply). Across all 9 patches they add only FIVE `mrb_define_method`
// calls (`Kernel#rand`, `Kernel#srand`, `Random#initialize|rand|srand`); the
// full mruby core method tables (`each`/`map`/`reduce`/…) live in the UNSHIPPED
// upstream mruby source. They therefore cannot be engine-derived. This curated
// table is plain-mruby-3.0.0 core, and it is the sole hand-maintained method
// list in the index. DragonRuby's own core-class extensions (map_2d, lerp, …)
// are engine-derived from `docs/api/*.md` and layered on top of this baseline;
// see EngineIndex.coreMethods.
export const CORE_BASELINE: Record<string, string[]> = {
  Array: [
    "each",
    "each_with_index",
    "map",
    "map!",
    "select",
    "reject",
    "reduce",
    "inject",
    "find",
    "include?",
    "length",
    "size",
    "count",
    "first",
    "last",
    "push",
    "pop",
    "shift",
    "unshift",
    "flatten",
    "compact",
    "uniq",
    "sort",
    "sort_by",
    "min",
    "max",
    "min_by",
    "max_by",
    "sum",
    "zip",
    "take",
    "drop",
    "empty?",
    "any?",
    "all?",
    "none?",
    "sample",
    "shuffle",
    "reverse",
    "join",
    "index",
    "delete",
    "delete_if",
    "concat",
    "each_slice",
    "group_by",
    "partition",
    "flat_map",
  ],
  Hash: [
    "each",
    "each_pair",
    "keys",
    "values",
    "map",
    "merge",
    "merge!",
    "select",
    "reject",
    "fetch",
    "store",
    "delete",
    "key?",
    "has_key?",
    "include?",
    "value?",
    "empty?",
    "length",
    "size",
    "any?",
    "all?",
    "to_a",
    "invert",
    "dig",
    "update",
    "find",
    "count",
    "sort_by",
    "min_by",
    "max_by",
    "sum",
    // DragonRuby Hash conveniences: shorthand that stamps a primitive_marker
    // so a plain hash renders as the named primitive. Not in the OSS source.
    "sprite!",
    "label!",
    "solid!",
    "border!",
    "line!",
  ],
  String: [
    "length",
    "size",
    "split",
    "sub",
    "gsub",
    "strip",
    "chomp",
    "upcase",
    "downcase",
    "capitalize",
    "include?",
    "start_with?",
    "end_with?",
    "index",
    "slice",
    "chars",
    "bytes",
    "lines",
    "to_i",
    "to_f",
    "to_s",
    "to_sym",
    "empty?",
    "reverse",
    "concat",
    "ljust",
    "rjust",
    "each_char",
    "each_line",
  ],
  Numeric: [
    "times",
    "upto",
    "downto",
    "step",
    "abs",
    "ceil",
    "floor",
    "round",
    "to_i",
    "to_f",
    "to_s",
    "zero?",
    "positive?",
    "negative?",
    "even?",
    "odd?",
    "clamp",
    "between?",
    "divmod",
    "succ",
    "pred",
  ],
};
