import { ensureDir, exists } from "@std/fs";
import { dirname, join } from "@std/path";

import type { Lockfile } from "./lockfile.ts";

/** Path to the generated require file, relative to the `mygame` directory. */
export const BUNDLE_PATH = "app/drenv_bundle.rb";

/** The require line a project's `main.rb` needs to load the bundle. */
export const BUNDLE_REQUIRE = "require 'app/drenv_bundle.rb'";

export const writeBundleFile = async (
  mygame: string,
  lock: Lockfile,
): Promise<void> => {
  const lines = [
    "# This file is generated by drenv. Do not edit.",
    "# Run `drenv bundle` to regenerate it.",
  ];

  for (const dep of lock.dependencies) {
    lines.push("", `# ${dep.name} (${dep.source})`);
    for (const path of dep.require) {
      lines.push(`require '${path}'`);
    }
  }

  lines.push("");

  const target = join(mygame, BUNDLE_PATH);
  await ensureDir(dirname(target));
  await Deno.writeTextFile(target, lines.join("\n"));
};

const VENDOR_IGNORE =
  "# Generated by drenv. Vendored dependencies are reproducible from drenv.lock.\n*\n";

/**
 * Ensures `mygame/vendor/.gitignore` ignores the whole directory, so vendored
 * dependencies stay out of version control. Self-contained — it never touches
 * the project's own `.gitignore`. Leaves an existing file untouched.
 */
export const ensureVendorIgnore = async (mygame: string): Promise<void> => {
  const dir = join(mygame, "vendor");
  if (!await exists(dir)) return;

  const path = join(dir, ".gitignore");
  if (!await exists(path)) {
    await Deno.writeTextFile(path, VENDOR_IGNORE);
  }
};
