import { parse, stringify } from "@std/toml";

export const LOCKFILE_VERSION = 1;

export type LockedDependency = {
  name: string;
  source: string;
  ref?: string;
  require: string[];
  integrity?: string;
};

export type Lockfile = {
  lockfile_version: number;
  manifest_digest: string;
  dependencies: LockedDependency[];
};

const HEADER = "# This file is generated by drenv. Do not edit.\n" +
  "# Run `drenv bundle` to update it.\n\n";

export const readLock = async (path: string): Promise<Lockfile | null> => {
  let text: string;

  try {
    text = await Deno.readTextFile(path);
  } catch {
    return null;
  }

  return parse(text) as unknown as Lockfile;
};

export const writeLock = async (
  path: string,
  lock: Lockfile,
): Promise<void> => {
  // Drop undefined fields so the lockfile stays clean: path deps carry no
  // integrity, and url/path deps carry no ref.
  const dependencies = lock.dependencies.map((dep) => ({
    name: dep.name,
    source: dep.source,
    ...(dep.ref ? { ref: dep.ref } : {}),
    require: dep.require,
    ...(dep.integrity ? { integrity: dep.integrity } : {}),
  }));

  const body = stringify({
    lockfile_version: lock.lockfile_version,
    manifest_digest: lock.manifest_digest,
    dependencies,
  });

  await Deno.writeTextFile(path, HEADER + body);
};
